### PR TITLE
Allow for optional parent container of game

### PR DESCRIPTION
**Pull request by niamu**
Pass a string for the HTML tag's ID as the third argument to `create-game`.

This change would allow for other elements on the page with the game for additional styling and functionality beyond just the game's canvas.

### CODE REVIEW

**Comment by oakes** [comment]
Maybe we should pass an optional map so we can provide other things in the future. Something like this:

```clojure
(defn create-game
  "Returns a game object."
  ([width height]
   (create-game width height {}))
  ([width height {:keys [parent]}]
   ...))
```

What do you think?

**Comment by niamu** [comment]
Yeah, definitely. I'll make that change.

Also, off-topic, but I've made some other improvements in `p5.tiledmap.js` on my own fork that add support for flipped and rotated Tiles that I needed for my own game. I initially considered opening a pull request to [linux-man/p5.tiledmap.js](https://github.com/linux-man/p5.tiledmap), but then realized that you had made some changes as well that only existed in this repository. I can open up a pull request for that as well.

**Comment by oakes** [comment]
Yep I had to fix a few bugs that were in it. A PR with your improvements would be great, please do!

**Comment by niamu** [comment]
I did my best to maintain the current indentation style, let me know if there is anything I missed.

**Comment by oakes** [comment]
Thanks!

**Pull request merged**
